-- Generated by scripts/availability-vectors.mjs from packages/core/src/availability-vectors.json.
-- Do not edit: change the vectors and run `pnpm db:vectors`.
--
-- The same cases run against the TypeScript rules in packages/core/src/vectors.test.ts
-- (R-04, M2-13).
begin;
select plan(20);

select tests.create_fixture();

-- a lesson inside the working day can be booked
delete from public.bookings where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.working_hours where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.availability_exceptions where instructor_id = 'b1000000-0000-0000-0000-000000000001';
update public.instructor_profiles set buffer_minutes = 30 where id = 'b1000000-0000-0000-0000-000000000001';
update public.businesses set settings = coalesce(settings, '{}'::jsonb) || jsonb_build_object('notice_hours', 24, 'horizon_weeks', 8) where id = 'bbbb0000-0000-0000-0000-000000000000';
insert into public.working_hours (instructor_id, business_id, weekday, start_time, end_time) values ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 2, '09:00', '17:00'), ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 7, '09:00', '13:00');
select is(
  private.slot_problem('b1000000-0000-0000-0000-000000000001', '2026-09-15T09:00:00Z', 60, 'learner', null, '2026-09-10T09:00:00Z'),
  null::text,
  'a lesson inside the working day can be booked'
);

-- the last lesson that fits before the day ends can be booked
delete from public.bookings where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.working_hours where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.availability_exceptions where instructor_id = 'b1000000-0000-0000-0000-000000000001';
update public.instructor_profiles set buffer_minutes = 30 where id = 'b1000000-0000-0000-0000-000000000001';
update public.businesses set settings = coalesce(settings, '{}'::jsonb) || jsonb_build_object('notice_hours', 24, 'horizon_weeks', 8) where id = 'bbbb0000-0000-0000-0000-000000000000';
insert into public.working_hours (instructor_id, business_id, weekday, start_time, end_time) values ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 2, '09:00', '17:00'), ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 7, '09:00', '13:00');
select is(
  private.slot_problem('b1000000-0000-0000-0000-000000000001', '2026-09-15T15:00:00Z', 60, 'learner', null, '2026-09-10T09:00:00Z'),
  null::text,
  'the last lesson that fits before the day ends can be booked'
);

-- a lesson that would run past the end of the day is outside availability
delete from public.bookings where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.working_hours where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.availability_exceptions where instructor_id = 'b1000000-0000-0000-0000-000000000001';
update public.instructor_profiles set buffer_minutes = 30 where id = 'b1000000-0000-0000-0000-000000000001';
update public.businesses set settings = coalesce(settings, '{}'::jsonb) || jsonb_build_object('notice_hours', 24, 'horizon_weeks', 8) where id = 'bbbb0000-0000-0000-0000-000000000000';
insert into public.working_hours (instructor_id, business_id, weekday, start_time, end_time) values ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 2, '09:00', '17:00'), ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 7, '09:00', '13:00');
select is(
  private.slot_problem('b1000000-0000-0000-0000-000000000001', '2026-09-15T16:00:00Z', 60, 'learner', null, '2026-09-10T09:00:00Z'),
  'OUTSIDE_AVAILABILITY',
  'a lesson that would run past the end of the day is outside availability'
);

-- a lesson before the day starts is outside availability
delete from public.bookings where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.working_hours where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.availability_exceptions where instructor_id = 'b1000000-0000-0000-0000-000000000001';
update public.instructor_profiles set buffer_minutes = 30 where id = 'b1000000-0000-0000-0000-000000000001';
update public.businesses set settings = coalesce(settings, '{}'::jsonb) || jsonb_build_object('notice_hours', 24, 'horizon_weeks', 8) where id = 'bbbb0000-0000-0000-0000-000000000000';
insert into public.working_hours (instructor_id, business_id, weekday, start_time, end_time) values ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 2, '09:00', '17:00'), ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 7, '09:00', '13:00');
select is(
  private.slot_problem('b1000000-0000-0000-0000-000000000001', '2026-09-15T07:00:00Z', 60, 'learner', null, '2026-09-10T09:00:00Z'),
  'OUTSIDE_AVAILABILITY',
  'a lesson before the day starts is outside availability'
);

-- a day the instructor does not work is outside availability
delete from public.bookings where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.working_hours where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.availability_exceptions where instructor_id = 'b1000000-0000-0000-0000-000000000001';
update public.instructor_profiles set buffer_minutes = 30 where id = 'b1000000-0000-0000-0000-000000000001';
update public.businesses set settings = coalesce(settings, '{}'::jsonb) || jsonb_build_object('notice_hours', 24, 'horizon_weeks', 8) where id = 'bbbb0000-0000-0000-0000-000000000000';
insert into public.working_hours (instructor_id, business_id, weekday, start_time, end_time) values ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 2, '09:00', '17:00'), ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 7, '09:00', '13:00');
select is(
  private.slot_problem('b1000000-0000-0000-0000-000000000001', '2026-09-16T10:00:00Z', 60, 'learner', null, '2026-09-10T09:00:00Z'),
  'OUTSIDE_AVAILABILITY',
  'a day the instructor does not work is outside availability'
);

-- a lesson inside a day that has been blocked out is outside availability
delete from public.bookings where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.working_hours where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.availability_exceptions where instructor_id = 'b1000000-0000-0000-0000-000000000001';
update public.instructor_profiles set buffer_minutes = 30 where id = 'b1000000-0000-0000-0000-000000000001';
update public.businesses set settings = coalesce(settings, '{}'::jsonb) || jsonb_build_object('notice_hours', 24, 'horizon_weeks', 8) where id = 'bbbb0000-0000-0000-0000-000000000000';
insert into public.working_hours (instructor_id, business_id, weekday, start_time, end_time) values ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 2, '09:00', '17:00'), ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 7, '09:00', '13:00');
insert into public.availability_exceptions (instructor_id, business_id, kind, starts_at, ends_at) values ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 'blocked', '2026-09-15T00:00:00Z', '2026-09-16T00:00:00Z');
select is(
  private.slot_problem('b1000000-0000-0000-0000-000000000001', '2026-09-15T09:00:00Z', 60, 'learner', null, '2026-09-10T09:00:00Z'),
  'OUTSIDE_AVAILABILITY',
  'a lesson inside a day that has been blocked out is outside availability'
);

-- a lesson beside an afternoon off can still be booked
delete from public.bookings where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.working_hours where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.availability_exceptions where instructor_id = 'b1000000-0000-0000-0000-000000000001';
update public.instructor_profiles set buffer_minutes = 30 where id = 'b1000000-0000-0000-0000-000000000001';
update public.businesses set settings = coalesce(settings, '{}'::jsonb) || jsonb_build_object('notice_hours', 24, 'horizon_weeks', 8) where id = 'bbbb0000-0000-0000-0000-000000000000';
insert into public.working_hours (instructor_id, business_id, weekday, start_time, end_time) values ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 2, '09:00', '17:00'), ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 7, '09:00', '13:00');
insert into public.availability_exceptions (instructor_id, business_id, kind, starts_at, ends_at) values ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 'blocked', '2026-09-15T12:00:00Z', '2026-09-15T16:00:00Z');
select is(
  private.slot_problem('b1000000-0000-0000-0000-000000000001', '2026-09-15T09:00:00Z', 60, 'learner', null, '2026-09-10T09:00:00Z'),
  null::text,
  'a lesson beside an afternoon off can still be booked'
);

-- a lesson that runs into an afternoon off is outside availability
delete from public.bookings where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.working_hours where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.availability_exceptions where instructor_id = 'b1000000-0000-0000-0000-000000000001';
update public.instructor_profiles set buffer_minutes = 30 where id = 'b1000000-0000-0000-0000-000000000001';
update public.businesses set settings = coalesce(settings, '{}'::jsonb) || jsonb_build_object('notice_hours', 24, 'horizon_weeks', 8) where id = 'bbbb0000-0000-0000-0000-000000000000';
insert into public.working_hours (instructor_id, business_id, weekday, start_time, end_time) values ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 2, '09:00', '17:00'), ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 7, '09:00', '13:00');
insert into public.availability_exceptions (instructor_id, business_id, kind, starts_at, ends_at) values ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 'blocked', '2026-09-15T12:00:00Z', '2026-09-15T16:00:00Z');
select is(
  private.slot_problem('b1000000-0000-0000-0000-000000000001', '2026-09-15T11:30:00Z', 60, 'learner', null, '2026-09-10T09:00:00Z'),
  'OUTSIDE_AVAILABILITY',
  'a lesson that runs into an afternoon off is outside availability'
);

-- extra hours on a day off can be booked
delete from public.bookings where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.working_hours where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.availability_exceptions where instructor_id = 'b1000000-0000-0000-0000-000000000001';
update public.instructor_profiles set buffer_minutes = 30 where id = 'b1000000-0000-0000-0000-000000000001';
update public.businesses set settings = coalesce(settings, '{}'::jsonb) || jsonb_build_object('notice_hours', 24, 'horizon_weeks', 8) where id = 'bbbb0000-0000-0000-0000-000000000000';
insert into public.working_hours (instructor_id, business_id, weekday, start_time, end_time) values ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 2, '09:00', '17:00'), ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 7, '09:00', '13:00');
insert into public.availability_exceptions (instructor_id, business_id, kind, starts_at, ends_at) values ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 'open', '2026-09-16T17:00:00Z', '2026-09-16T20:00:00Z');
select is(
  private.slot_problem('b1000000-0000-0000-0000-000000000001', '2026-09-16T17:00:00Z', 60, 'learner', null, '2026-09-10T09:00:00Z'),
  null::text,
  'extra hours on a day off can be booked'
);

-- a lesson that clashes with one already booked is taken
delete from public.bookings where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.working_hours where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.availability_exceptions where instructor_id = 'b1000000-0000-0000-0000-000000000001';
update public.instructor_profiles set buffer_minutes = 30 where id = 'b1000000-0000-0000-0000-000000000001';
update public.businesses set settings = coalesce(settings, '{}'::jsonb) || jsonb_build_object('notice_hours', 24, 'horizon_weeks', 8) where id = 'bbbb0000-0000-0000-0000-000000000000';
insert into public.working_hours (instructor_id, business_id, weekday, start_time, end_time) values ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 2, '09:00', '17:00'), ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 7, '09:00', '13:00');
insert into public.bookings (business_id, instructor_id, learner_id, lesson_type_id, starts_at, ends_at, buffer_minutes, status, price_pence, source) values ('bbbb0000-0000-0000-0000-000000000000', 'b1000000-0000-0000-0000-000000000001', 'c0000000-0000-0000-0000-000000000002', 'b2000000-0000-0000-0000-000000000001', '2026-09-15T09:30:00Z', '2026-09-15T10:30:00Z', 0, 'confirmed', 4200, 'instructor');
select is(
  private.slot_problem('b1000000-0000-0000-0000-000000000001', '2026-09-15T09:00:00Z', 60, 'learner', null, '2026-09-10T09:00:00Z'),
  'SLOT_TAKEN',
  'a lesson that clashes with one already booked is taken'
);

-- a lesson that would leave no travel time before the next one is taken
delete from public.bookings where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.working_hours where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.availability_exceptions where instructor_id = 'b1000000-0000-0000-0000-000000000001';
update public.instructor_profiles set buffer_minutes = 30 where id = 'b1000000-0000-0000-0000-000000000001';
update public.businesses set settings = coalesce(settings, '{}'::jsonb) || jsonb_build_object('notice_hours', 24, 'horizon_weeks', 8) where id = 'bbbb0000-0000-0000-0000-000000000000';
insert into public.working_hours (instructor_id, business_id, weekday, start_time, end_time) values ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 2, '09:00', '17:00'), ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 7, '09:00', '13:00');
insert into public.bookings (business_id, instructor_id, learner_id, lesson_type_id, starts_at, ends_at, buffer_minutes, status, price_pence, source) values ('bbbb0000-0000-0000-0000-000000000000', 'b1000000-0000-0000-0000-000000000001', 'c0000000-0000-0000-0000-000000000002', 'b2000000-0000-0000-0000-000000000001', '2026-09-15T11:00:00Z', '2026-09-15T12:00:00Z', 0, 'confirmed', 4200, 'instructor');
select is(
  private.slot_problem('b1000000-0000-0000-0000-000000000001', '2026-09-15T09:40:00Z', 60, 'learner', null, '2026-09-10T09:00:00Z'),
  'SLOT_TAKEN',
  'a lesson that would leave no travel time before the next one is taken'
);

-- a lesson that finishes its travel time exactly as the next begins can be booked
delete from public.bookings where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.working_hours where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.availability_exceptions where instructor_id = 'b1000000-0000-0000-0000-000000000001';
update public.instructor_profiles set buffer_minutes = 30 where id = 'b1000000-0000-0000-0000-000000000001';
update public.businesses set settings = coalesce(settings, '{}'::jsonb) || jsonb_build_object('notice_hours', 24, 'horizon_weeks', 8) where id = 'bbbb0000-0000-0000-0000-000000000000';
insert into public.working_hours (instructor_id, business_id, weekday, start_time, end_time) values ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 2, '09:00', '17:00'), ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 7, '09:00', '13:00');
insert into public.bookings (business_id, instructor_id, learner_id, lesson_type_id, starts_at, ends_at, buffer_minutes, status, price_pence, source) values ('bbbb0000-0000-0000-0000-000000000000', 'b1000000-0000-0000-0000-000000000001', 'c0000000-0000-0000-0000-000000000002', 'b2000000-0000-0000-0000-000000000001', '2026-09-15T11:00:00Z', '2026-09-15T12:00:00Z', 0, 'confirmed', 4200, 'instructor');
select is(
  private.slot_problem('b1000000-0000-0000-0000-000000000001', '2026-09-15T09:30:00Z', 60, 'learner', null, '2026-09-10T09:00:00Z'),
  null::text,
  'a lesson that finishes its travel time exactly as the next begins can be booked'
);

-- a lesson too soon for the notice the Business asks for is refused
delete from public.bookings where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.working_hours where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.availability_exceptions where instructor_id = 'b1000000-0000-0000-0000-000000000001';
update public.instructor_profiles set buffer_minutes = 30 where id = 'b1000000-0000-0000-0000-000000000001';
update public.businesses set settings = coalesce(settings, '{}'::jsonb) || jsonb_build_object('notice_hours', 24, 'horizon_weeks', 8) where id = 'bbbb0000-0000-0000-0000-000000000000';
insert into public.working_hours (instructor_id, business_id, weekday, start_time, end_time) values ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 2, '09:00', '17:00'), ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 7, '09:00', '13:00');
select is(
  private.slot_problem('b1000000-0000-0000-0000-000000000001', '2026-09-15T09:00:00Z', 60, 'learner', null, '2026-09-15T08:00:00Z'),
  'NOTICE_TOO_SHORT',
  'a lesson too soon for the notice the Business asks for is refused'
);

-- the same lesson booked by the instructor is fine
delete from public.bookings where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.working_hours where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.availability_exceptions where instructor_id = 'b1000000-0000-0000-0000-000000000001';
update public.instructor_profiles set buffer_minutes = 30 where id = 'b1000000-0000-0000-0000-000000000001';
update public.businesses set settings = coalesce(settings, '{}'::jsonb) || jsonb_build_object('notice_hours', 24, 'horizon_weeks', 8) where id = 'bbbb0000-0000-0000-0000-000000000000';
insert into public.working_hours (instructor_id, business_id, weekday, start_time, end_time) values ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 2, '09:00', '17:00'), ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 7, '09:00', '13:00');
select is(
  private.slot_problem('b1000000-0000-0000-0000-000000000001', '2026-09-15T09:00:00Z', 60, 'instructor', null, '2026-09-15T08:00:00Z'),
  null::text,
  'the same lesson booked by the instructor is fine'
);

-- an instructor may book outside their own availability
delete from public.bookings where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.working_hours where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.availability_exceptions where instructor_id = 'b1000000-0000-0000-0000-000000000001';
update public.instructor_profiles set buffer_minutes = 30 where id = 'b1000000-0000-0000-0000-000000000001';
update public.businesses set settings = coalesce(settings, '{}'::jsonb) || jsonb_build_object('notice_hours', 24, 'horizon_weeks', 8) where id = 'bbbb0000-0000-0000-0000-000000000000';
insert into public.working_hours (instructor_id, business_id, weekday, start_time, end_time) values ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 2, '09:00', '17:00'), ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 7, '09:00', '13:00');
select is(
  private.slot_problem('b1000000-0000-0000-0000-000000000001', '2026-09-15T19:00:00Z', 60, 'instructor', null, '2026-09-10T09:00:00Z'),
  null::text,
  'an instructor may book outside their own availability'
);

-- an instructor may not book on top of a lesson they already have
delete from public.bookings where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.working_hours where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.availability_exceptions where instructor_id = 'b1000000-0000-0000-0000-000000000001';
update public.instructor_profiles set buffer_minutes = 30 where id = 'b1000000-0000-0000-0000-000000000001';
update public.businesses set settings = coalesce(settings, '{}'::jsonb) || jsonb_build_object('notice_hours', 24, 'horizon_weeks', 8) where id = 'bbbb0000-0000-0000-0000-000000000000';
insert into public.working_hours (instructor_id, business_id, weekday, start_time, end_time) values ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 2, '09:00', '17:00'), ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 7, '09:00', '13:00');
insert into public.bookings (business_id, instructor_id, learner_id, lesson_type_id, starts_at, ends_at, buffer_minutes, status, price_pence, source) values ('bbbb0000-0000-0000-0000-000000000000', 'b1000000-0000-0000-0000-000000000001', 'c0000000-0000-0000-0000-000000000002', 'b2000000-0000-0000-0000-000000000001', '2026-09-15T09:30:00Z', '2026-09-15T10:30:00Z', 0, 'confirmed', 4200, 'instructor');
select is(
  private.slot_problem('b1000000-0000-0000-0000-000000000001', '2026-09-15T09:00:00Z', 60, 'instructor', null, '2026-09-10T09:00:00Z'),
  'SLOT_TAKEN',
  'an instructor may not book on top of a lesson they already have'
);

-- a lesson further ahead than the diary is open is refused
delete from public.bookings where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.working_hours where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.availability_exceptions where instructor_id = 'b1000000-0000-0000-0000-000000000001';
update public.instructor_profiles set buffer_minutes = 30 where id = 'b1000000-0000-0000-0000-000000000001';
update public.businesses set settings = coalesce(settings, '{}'::jsonb) || jsonb_build_object('notice_hours', 24, 'horizon_weeks', 8) where id = 'bbbb0000-0000-0000-0000-000000000000';
insert into public.working_hours (instructor_id, business_id, weekday, start_time, end_time) values ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 2, '09:00', '17:00'), ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 7, '09:00', '13:00');
select is(
  private.slot_problem('b1000000-0000-0000-0000-000000000001', '2026-12-15T09:00:00Z', 60, 'learner', null, '2026-09-10T09:00:00Z'),
  'BEYOND_HORIZON',
  'a lesson further ahead than the diary is open is refused'
);

-- the morning the clocks go forward, the hour that does not happen cannot be booked
delete from public.bookings where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.working_hours where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.availability_exceptions where instructor_id = 'b1000000-0000-0000-0000-000000000001';
update public.instructor_profiles set buffer_minutes = 30 where id = 'b1000000-0000-0000-0000-000000000001';
update public.businesses set settings = coalesce(settings, '{}'::jsonb) || jsonb_build_object('notice_hours', 24, 'horizon_weeks', 8) where id = 'bbbb0000-0000-0000-0000-000000000000';
insert into public.working_hours (instructor_id, business_id, weekday, start_time, end_time) values ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 7, '00:00', '06:00');
select is(
  private.slot_problem('b1000000-0000-0000-0000-000000000001', '2026-03-29T01:00:00Z', 60, 'learner', null, '2026-03-20T09:00:00Z'),
  null::text,
  'the morning the clocks go forward, the hour that does not happen cannot be booked'
);

-- the morning the clocks go back, the repeated hour is one o clock the first time
delete from public.bookings where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.working_hours where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.availability_exceptions where instructor_id = 'b1000000-0000-0000-0000-000000000001';
update public.instructor_profiles set buffer_minutes = 30 where id = 'b1000000-0000-0000-0000-000000000001';
update public.businesses set settings = coalesce(settings, '{}'::jsonb) || jsonb_build_object('notice_hours', 24, 'horizon_weeks', 8) where id = 'bbbb0000-0000-0000-0000-000000000000';
insert into public.working_hours (instructor_id, business_id, weekday, start_time, end_time) values ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 7, '00:00', '06:00');
select is(
  private.slot_problem('b1000000-0000-0000-0000-000000000001', '2026-10-25T00:30:00Z', 60, 'learner', null, '2026-10-16T09:00:00Z'),
  null::text,
  'the morning the clocks go back, the repeated hour is one o clock the first time'
);

-- a lesson on the clock change Sunday outside the hours worked is still refused
delete from public.bookings where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.working_hours where instructor_id = 'b1000000-0000-0000-0000-000000000001';
delete from public.availability_exceptions where instructor_id = 'b1000000-0000-0000-0000-000000000001';
update public.instructor_profiles set buffer_minutes = 30 where id = 'b1000000-0000-0000-0000-000000000001';
update public.businesses set settings = coalesce(settings, '{}'::jsonb) || jsonb_build_object('notice_hours', 24, 'horizon_weeks', 8) where id = 'bbbb0000-0000-0000-0000-000000000000';
insert into public.working_hours (instructor_id, business_id, weekday, start_time, end_time) values ('b1000000-0000-0000-0000-000000000001', 'bbbb0000-0000-0000-0000-000000000000', 7, '00:00', '06:00');
select is(
  private.slot_problem('b1000000-0000-0000-0000-000000000001', '2026-10-25T07:00:00Z', 60, 'learner', null, '2026-10-16T09:00:00Z'),
  'OUTSIDE_AVAILABILITY',
  'a lesson on the clock change Sunday outside the hours worked is still refused'
);

select * from finish();
rollback;
