/**
 * Turns the shared availability vectors into a pgTAP test (M2-13).
 *
 * The vectors live in packages/core/src/availability-vectors.json and are run by Vitest
 * against the TypeScript rules. This writes the same cases out as SQL so `supabase test db`
 * runs them against the rules in the database, and the two can never quietly disagree.
 *
 * Run with `pnpm db:vectors`, which `pnpm db:test` does for you.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const source = path.join(root, 'packages/core/src/availability-vectors.json');
const target = path.join(root, 'supabase/tests/31_availability_vectors_test.sql');

/** Fixture ids from supabase/seeds/test_helpers.sql. */
const INSTRUCTOR = 'b1000000-0000-0000-0000-000000000001';
const BUSINESS = 'bbbb0000-0000-0000-0000-000000000000';
const LESSON_TYPE = 'b2000000-0000-0000-0000-000000000001';
const LEARNER = 'c0000000-0000-0000-0000-000000000002';

const quote = (value) => `'${String(value).replaceAll("'", "''")}'`;

const { defaults, vectors } = JSON.parse(readFileSync(source, 'utf8'));

const lines = [
  '-- Generated by scripts/availability-vectors.mjs from packages/core/src/availability-vectors.json.',
  '-- Do not edit: change the vectors and run `pnpm db:vectors`.',
  '--',
  '-- The same cases run against the TypeScript rules in packages/core/src/vectors.test.ts',
  '-- (R-04, M2-13).',
  'begin;',
  `select plan(${vectors.length});`,
  '',
  'select tests.create_fixture();',
  '',
];

vectors.forEach((vector, index) => {
  const hours = vector.hours ?? defaults.hours;
  const rules = { ...defaults.rules, ...(vector.rules ?? {}) };
  const now = vector.now ?? defaults.now;
  const by = vector.by ?? defaults.by;
  // No savepoints: rolling one back would undo what pgTAP has recorded so far. Each vector
  // clears what the last one left instead.
  lines.push(`-- ${vector.name}`);
  lines.push(
    `delete from public.bookings where instructor_id = ${quote(INSTRUCTOR)};`,
    `delete from public.working_hours where instructor_id = ${quote(INSTRUCTOR)};`,
    `delete from public.availability_exceptions where instructor_id = ${quote(INSTRUCTOR)};`,
    `update public.instructor_profiles set buffer_minutes = ${rules.bufferMinutes} where id = ${quote(INSTRUCTOR)};`,
    `update public.businesses set settings = coalesce(settings, '{}'::jsonb) || ` +
      `jsonb_build_object('notice_hours', ${rules.noticeHours}, 'horizon_weeks', ${rules.horizonWeeks}) ` +
      `where id = ${quote(BUSINESS)};`,
  );

  if (hours.length > 0) {
    const values = hours
      .map(
        (hour) =>
          `(${quote(INSTRUCTOR)}, ${quote(BUSINESS)}, ${hour.weekday}, ${quote(hour.start)}, ${quote(hour.end)})`,
      )
      .join(', ');
    lines.push(
      `insert into public.working_hours (instructor_id, business_id, weekday, start_time, end_time) values ${values};`,
    );
  }

  for (const exception of vector.exceptions ?? []) {
    lines.push(
      `insert into public.availability_exceptions (instructor_id, business_id, kind, starts_at, ends_at) values ` +
        `(${quote(INSTRUCTOR)}, ${quote(BUSINESS)}, ${quote(exception.kind)}, ${quote(exception.startsAt)}, ${quote(exception.endsAt)});`,
    );
  }

  for (const busy of vector.busy ?? []) {
    // Buffer zero, so the row blocks exactly the range the vector names.
    lines.push(
      `insert into public.bookings (business_id, instructor_id, learner_id, lesson_type_id, starts_at, ends_at, ` +
        `buffer_minutes, status, price_pence, source) values (${quote(BUSINESS)}, ${quote(INSTRUCTOR)}, ` +
        `${quote(LEARNER)}, ${quote(LESSON_TYPE)}, ${quote(busy.startsAt)}, ${quote(busy.endsAt)}, 0, 'confirmed', 4200, 'instructor');`,
    );
  }

  const expected = vector.expect === null ? 'null::text' : quote(vector.expect);
  lines.push(
    `select is(`,
    `  private.slot_problem(${quote(INSTRUCTOR)}, ${quote(vector.startsAt)}, ${rules.durationMinutes}, ${quote(by)}, null, ${quote(now)}),`,
    `  ${expected},`,
    `  ${quote(vector.name)}`,
    `);`,
    '',
  );
});

lines.push('select * from finish();', 'rollback;', '');

writeFileSync(target, lines.join('\n'), 'utf8');
console.log(`Wrote ${vectors.length} availability vectors to ${path.relative(root, target)}`);
